### PR TITLE
Fixed problem with IE9 and the labels position

### PR DESCRIPTION
**Pull request by carlosreig**
Changed the CSS property used to set the label position from -[browser]-transform to top and left properties.

### CODE REVIEW

**Comment by markrcote** [comment]
IE 9 should be handled correctly. The plug-in attempts to detect if the browser is IE 9, and, if so, it uses a mix of CSS positioning and IE transforms (via the IeTransformAxisLabel object). Is it not working for you?

**Comment by carlosreig** [comment]
Hello Mark,

The browser detection worked fine and the label was well rotated, but bad positioned. It was positioned very far of the chart. When I changed the browser-depending CSS property for translate the label, it worked well. I also done tests with Chrome and Firefox (I don't remember the version) and the changes work too.

**Comment by markrcote** [comment]
Sorry, my earlier comment was wrong--I was thinking of IE 8.

IE 9 should fully support CSS transforms (as long as the "-ms-" prefix is used). I cannot reproduce your issue, and I'd like to stick with all proper CSS transforms instead of a mix of transforms and positioning if possible. Can you provide some example code and a screen shot?

**Comment by markrcote** [comment]
No response in a long time, closing.

**Pull request closed without merging**
